//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingJackpotModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeeklyPlay
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public Nullable<int> Pins { get; set; }
        public System.DateTime Play_Date { get; set; }
        public Nullable<decimal> Payout_Amount { get; set; }
    
        public virtual User User { get; set; }
    }
}
